language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd camping-calamar-front
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master

